#!/usr/bin/env python
# coding: utf-8

# In[5]:


import umap.umap_ as umap
import scipy.sparse
from sklearn.manifold import MDS
import numpy as np
import random

# In[3]:


def umap_from_knn_py(adj,n_neighbors = 10,seed = 1024):
    random.seed(seed)
    adj_matrix_sparse = scipy.sparse.csr_matrix(adj)

    # Apply UMAP using the kNN graph directly
    umap_model_precomputed = umap.UMAP(metric='precomputed',n_neighbors = n_neighbors)
    umap_embedding_precomputed = umap_model_precomputed.fit_transform(adj_matrix_sparse)
    
    return(umap_embedding_precomputed)


# In[7]:


def mds_from_knn_py(adj,n_components = 20):
    dense = np.full(adj.shape, 1e10)
    dense[adj.nonzero()] = adj.data
    
    mds = MDS(n_components=n_components, dissimilarity="precomputed")
    mds_embedding = mds.fit_transform(dense)
    
    return(mds_embedding)


# In[ ]:




